import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJs - Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="font-bold">
          Jesus<span className="font-normal">Macias</span>
        </h1>
      </main>
    </>
  );
}
